### ISSUE TITLE
Error: Pusher Beams does not support this browser version (Web Push not supported) on Iphones with IOS 16.1.1, 16.5.1, 17

### ISSUE THREAD

**Issue by apangr** [pusher/push-notifications-web#147] opened 2023-09-20 19:51 UTC
I have tried to load my web application that uses Pusher Beams for notifications, and on iPhones with IOS 16.6.1, 16.5.1 and 17 (which I have tested on), the website goes blank and receives this error:
**Error:** Pusher Beams does not support this browser version (Web Push not supported)
It was tested in the following browsers: 
 Safari 16.6.1, 16.5.1 and 17
 Chrome  117.0.5938.108  and 109.0.5414.112

**Comment by apangr** [comment] 2023-09-21 03:06
![error pusher beams](https://github.com/pusher/push-notifications-web/assets/48444415/883272fe-69ce-490d-844c-06b121fadbf9)

**Comment by benw-pusher** [comment] 2023-09-21 08:22
At this time we don't support web push on iOS devices. 
I will close this as a duplicate of https://github.com/pusher/push-notifications-web/issues/146.

**Closed by benw-pusher** 2023-09-21 08:22 UTC
