### ISSUE TITLE
[Feature Request] isSupported as a function

### ISSUE THREAD

**Issue by natoehv** [pusher/push-notifications-web#101] opened 2022-03-18 15:14 UTC
Hi all, when we use the `Client` constructor we have to enclose it in a try/catch statement, so it would be great if we could ask for the beams support before creating the instance, something like this:
```typescript
import * as PusherPushNotifications from '@pusher/push-notifications-web';

if (PusherPushNotifications.isSupported()) {
  const beamsClient = new PusherPushNotifications.Client(...)
  ...
}
```
in that way, we can avoid using the try/catch statement, and we could use it in others places to take different decisions.

greetings!

**Comment by benjamin-tang-pusher** [comment] 2022-04-20 18:57
Thanks for the suggestion. We will add this to our feature request list. I will close this issue as it is not a bug.

**Closed by benjamin-tang-pusher** 2022-04-20 18:57 UTC
