### ISSUE TITLE
TS | hide_notification_if_site_has_focus

### ISSUE THREAD

**Issue by v1narth** [pusher/push-notifications-web#108] opened 2022-07-17 09:54 UTC
Seems like `hide_notification_if_site_has_focus?: string` should be `boolean instead`.
If set to any `string` as defined by the types, it throws an error on runtime:

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/23546753/179393032-fcf0c2bc-2005-4a2d-8202-04d4a0d6960e.png">

**Using v1.2.5**

**Comment by benw-pusher** [comment] 2022-08-09 10:43
I believe this is raised in the wrong repo - and is a duplicate of https://github.com/pusher/push-notifications-node/issues/49. 
I have raised a PR, linked above, to resolve but will close this issue out as it is not an issue with the web repo.

**Closed by benw-pusher** 2022-08-09 10:43 UTC
